DROP SEQUENCE NOTICE_SEQ;
CREATE SEQUENCE NOTICE_SEQ NOCACHE;

DROP TABLE NOTICE;
CREATE TABLE NOTICE(
    NOTICE_NO    NUMBER              NOT NULL,
    GUBUN       NUMBER              NOT NULL,
    TITLE       VARCHAR2(1000 BYTE) NOT NULL,
    CONTENT     CLOB,
    CONSTRAINT PK_NOTICE PRIMARY KEY(NOTICE_NO)
    );